### ISSUE TITLE
example sine_synth.rs doesn't build

### ISSUE THREAD

**Issue by crsaracco** [rust-dsp/rust-vst#18] opened 2017-11-14 02:40 UTC
#### Platform information

 - Arch Linux
 - Tested with both rustc 1.21.0 (stable) and rustc 1.23.0 (nightly)

#### Compilation error

I get these errors when I try to build the `examples/sine_synth.rs` example:

```rust
error[E0532]: expected tuple struct/variant, found struct variant `Event::Midi`
  --> src/lib.rs:96:17
   |
96 |                 Event::Midi(ev) => self.process_midi_event(ev.data),
   |                 ^^^^^^^^^^^ did you mean `Event::Midi { /* fields */ }`?

error[E0053]: method `process_events` has an incompatible type for trait
   --> src/lib.rs:93:5
    |
93  | /     fn process_events(&mut self, events: &Events) {
94  | |         for event in events.events() {
95  | |             match event {
96  | |                 Event::Midi(ev) => self.process_midi_event(ev.data),
...   |
100 | |         }
101 | |     }
    | |_____^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `fn(&mut SineSynth, std::vec::Vec<vst2::event::Event<'_>>)`
               found type `fn(&mut SineSynth, &vst2::api::Events)`

error[E0053]: method `process` has an incompatible type for trait
   --> src/lib.rs:107:5
    |
107 | /     fn process(&mut self, buffer: &mut AudioBuffer<f32>) {
108 | |         let samples = buffer.samples();
109 | |
110 | |         let per_sample = self.time_per_sample();
...   |
137 | |         self.note_duration += samples as f64 * per_sample;
138 | |     }
    | |_____^ expected struct `vst2::buffer::AudioBuffer`, found mutable reference
    |
    = note: expected type `fn(&mut SineSynth, vst2::buffer::AudioBuffer<'_, f32>)`
               found type `fn(&mut SineSynth, &mut vst2::buffer::AudioBuffer<'_, f32>)`

error: aborting due to 3 previous errors
```

**Comment by zyvitski** [comment] 2017-11-14 03:00
Cannot reproduce on OS X, @Boscop can you verify on windows when you get a chance?

**Comment by crsaracco** [comment] 2017-11-14 03:01
Whoops, should mention I'm testing on Arch Linux. Will edit the original post with that data.

**Comment by crsaracco** [comment] 2017-11-14 03:28
Ok, so I *think* it's my cargo pulling a version different from this repo. When I do `cargo doc` it generates documentation slightly different from [this online documentation](https://rust-dsp.github.io/rust-vst/vst2/event/enum.Event.html).

This makes sense; when I check crates.io [here](https://crates.io/crates/vst2) I see the crate was last updated 2016-09-07.

**Comment by crsaracco** [comment] 2017-11-14 03:38
Alright, so yeah it was a different version. I simply changed my `Cargo.toml` to point to this repo instead of `0.0.1` and everything works:

```toml
[dependencies]
vst2 = { git = "https://github.com/rust-dsp/rust-vst" }
```

I'd recommend changing the `readme.md` to reflect this, or updating crates.io. :)

**Comment by piedoom** [comment] 2017-11-14 04:51
This goes along with #4, which is a priority right now, so this will be fixed soon.  In the meantime, I'll update the README.md to avoid confusion.

**Closed** 2017-11-14 04:53 UTC
